# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-05 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='all',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='mistakes',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='data',
            field=models.TextField(blank=True, help_text='Служебное поле. В будущем вы его не увидите.', null=True, verbose_name='JSON'),
        ),
    ]
