# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-20 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180705_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='data',
            field=models.TextField(blank=True, help_text='Поле для хранения JSON информации', null=True, verbose_name='Данные'),
        ),
    ]
