# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latin', '0003_auto_20180619_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bone',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отображать данный элемент на сайте'),
        ),
    ]
