# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-12 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latin', '0009_auto_20180703_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bone',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='latin/bones', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bonetype',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='latin/bones/covers', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='muscle',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='latin/muscles', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='muscletype',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='latin/muscles/covers', verbose_name='Изображение'),
        ),
    ]
