# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-20 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latin', '0010_auto_20180712_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bone',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='muscle',
            name='is_active',
        ),
    ]
