# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-20 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20180720_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='reference', verbose_name='Изображение')),
                ('link', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ссылка')),
            ],
        ),
    ]
