# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-20 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_auto_20180720_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Строка для вставки в статью'),
        ),
    ]
