# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-02 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('histology', '0002_auto_20180801_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('variable', models.CharField(max_length=32, verbose_name='Переменная')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='histology/covers', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.AlterField(
            model_name='sample',
            name='info',
            field=models.TextField(blank=True, help_text='В данном поле вы можете использовать теги HTML', null=True, verbose_name='Информация о препарате'),
        ),
        migrations.AddField(
            model_name='sample',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='histology.SampleSection', verbose_name='Раздел'),
        ),
    ]
