# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-20 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20180620_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bone',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
    ]
