# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-24 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20180620_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(max_length=64, verbose_name='Название на русском')),
                ('name_lat', models.CharField(max_length=64, verbose_name='Название на латинском')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='muscles', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать данный элемент на сайте')),
            ],
            options={
                'verbose_name': 'Мышца',
                'verbose_name_plural': 'Мышцы',
            },
        ),
        migrations.CreateModel(
            name='MuscleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('variable', models.CharField(max_length=32, verbose_name='Переменная')),
            ],
            options={
                'verbose_name': 'Тип мышцы',
                'verbose_name_plural': 'Типы мышц',
            },
        ),
        migrations.AddField(
            model_name='muscle',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='content.MuscleType', verbose_name='Отдел'),
        ),
    ]
