# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-03 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20180624_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonetype',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='bones/covers', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='muscletype',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='muscles/covers', verbose_name='Изображение'),
        ),
    ]
